homefinder/homefinder/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^homesapp/',include('homesapp.urls')),
]

homefinder/homesapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .import views


urlpatterns = [
    #/homesapp
    url(r'^$', views.IndexView.as_view(),name='index'),
    #/homesapp/1
    url(r'^(?P<pk>[0-9]+)/$',views.LocationView.as_view(),name='property'),
    #homesapp/1/2
    url(r'^([0-9]+)/(?P<pk>[0-9]+)/$', views.PropertyDetail.as_view(),name='propertyview'),
]

homefinder/homesapp/models.py
from django.db import models
# Create your models here.


class Location(models.Model):
    location_name = models.CharField(max_length = 200)
    location_type = models.CharField(max_length = 200)

    def __str__(self):
        return self.location_name


class Property(models.Model):
    location = models.ForeignKey(Location, on_delete = models.CASCADE)
    property_name = models.CharField(max_length =200)
    area = models.CharField(max_length = 200)
    price = models.CharField(max_length=200)
    floor = models.CharField(max_length=200)
    direction = models.CharField(max_length=200)
    postadd = models.CharField(max_length=200)
    image_url = models.CharField(max_length=500)
    age = models.CharField(max_length=200)


    def __str__(self):
        return self.property_name

homefinder/homesapp/views.py
from django.shortcuts import render
from django.views import generic
from .models import Location
from .models import Property

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'homesapp/index.html'

    def get_queryset(self):
        return Location.objects.all()



class LocationView(generic.DetailView):
    model = Location
    template_name = 'homesapp/locationview.html'

class PropertyDetail(generic.DetailView):
    model = Property
    template_name = 'homesapp/propertyview.html'

homefinder/homesapp/templates/homesapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>REAL ESTATE </title>
</head>
<body>
<div class="navbar navbar-inverse">
<div class="container-fluid">
    <div class="navbar-header"></div>
    <a class="navbar-brand" href="#" style="font-family:cursive;font-weight:bold;font-size:20px;">Property Arena</a>
</div>
   <ul class="nav navbar-nav">
    <li class="active"><a href="#">Home </a>
    </li>
    <li > <a href="#">About </a>
    </li>
       <li><a href="#"> page 2</a></li>
       <li><a href="#"> Page 3</a></li>

    <li class="nav-item">
      <a class="nav-link" href="#">Page 3</a>
    </li>
  </ul>

    <ul class="nav navbar-nav navbar-right" >

    <li><a href="#">Sign Up </a></li>
       <li><a href="#"> Login</a></li>
       <li><a href="#"> Contact Us</a></li>
    </ul>
</div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

homefinder/homesapp/templates/homesapp/index.html
{% extends 'homesapp/base.html' %}
<html>
<head>
</head>
{% block body %}
<style>
    .p1
    {

        font-family:"Comic Sans MS", cursive, sans-serif;
        margin:0 auto;
        margin-left:250px;
        quotes:"\201C""\201D""\2018""\2019";
          padding: 10px 20px;
          line-height: 1.4;
     }
     .p1:before {
  content: open-quote;
  display: inline;
  height: 0;
  line-height: 0;
  left: -3px;
  position: relative;
  top: 12px;
  color: black;
  font-size: 2em;
}
.p1::after {
  content: close-quote;
  display: inline;
  height: 0;
  line-height: 1;
  left: 1px;
  position: relative;
  top: 12px;
  color: black;
  font-size: 2em;
}


</style>
<body style="background-color:skyblue;" >

<div class="container">
    <div class="container">
        <div class="jumbotron" style="background-color: #b2004c;">
            <h1 style=" text-shadow: 2px 2px 5px white;"><center>PROPERTY ARENA </center></h1>
            <p style="font-size:20px;color:black;" class="p1"><i>With us, it's not just a house, you find a Home.</i> </p>
        </div>
    </div>
   <center> <h1 style="font-family:Comic Sans MS;font-size:25px; margin:7px;margin-top:-10px;"> SELECT YOUR LOCATION </h1></center>
<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">Locations</div>

        {% for location in object_list %}
       <div class="panel-body " style="display:inline-block;"> <a href="/homesapp/{{location.id}}">{{location.location_name}}</a><br>


       </div>
        {% endfor %}
    </div>
</div>
</div>
</body>
{% endblock %}
</html>

homefinder/homesapp/templates/homesapp/locationview.html
<!--This is location page
-->

{% extends 'homesapp/base.html' %}


{% block body %}
<html>

<head>
</head>
<body>
<div class="col-md-1">

</div>
<div class="col-md-8">
    <h1>Properties in {{location.location_name}}</h1>

    <div class="panel-group">
        {% for place in location.property_set.all %}

        <div class="panel panel-primary">
            <div class="panel-heading ">{{place.property_name}}</div>
            <div class="panel-body">
                <div class="col-md-4">
                <img src="{{place.image_url}}" height="200" width="200">
                </div>
                <div class="col-md=6">
                    <table class="table">
                        <tbody>
                        <tr>
                            <td>
                                <label><b>Area Sqft.</b></label></td>
                            <td>{{place.area}}</td>
                        </tr>

                            <tr>
                            <td>
                                <label><b>Price</b></label></td>
                            <td>{{place.price}}</td>
                        </tr>
                        <tr>
                            <td>
                                <label><b>No. of floors</b></label></td>
                            <td>{{place.floor}}</td>
                        </tr>
                        <tr>
                            <td>
                                <label><b>Address</b></label></td>
                            <td>{{place.postadd}}</td>
                        </tr>

                        <tr>
                            <td>

                            </td>
                            <td>

                            </td>

                            <td> <a class="btn btn-success" href="/homesapp/{{location.id}}/{{place.id}}">View Details</a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            </div>
        {% endfor %}
            </div>
    </div>
</body>
</html>



    {{ place.property_name }}</a>

{% endblock %}

homefinder/homesapp/templates/homesapp/propertyview.html
{% extends 'homesapp/base.html' %}
{% block body %}
<!DOCTYPE html>
<html>
<head>
     <style>
  #map {
    height: 100%;
  }
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
</style>

</head>
<body>
<div class="row">
<div class="col-md-1">
</div>
    <div class="col-md-3">
        <div class="thumbnail">
            <img src = "{{property.image_url}}" height="420" width="420">
        <div class="caption">
            <p> {{property.property_name}}</p>
             </div>
        </div>
    </div>


<div class="col-md-8">
    <div class="container">
        <div class="panel-group">
            <div class="panel panel-primary">
                <div class="panel-heading">Property Details</div>
                <div class="panel-body">
                    <table class="table">
                        <tbody>
                        <tr>
                            <td>
                                <label><b>Area Sqft. </b></label>
                            </td>
                            <td>
                                {{property.area}}
                            </td>
                        </tr>
                         <tr>
                            <td>
                                <label><b>Price </b></label>
                            </td>
                            <td>
                                {{property.price}}
                            </td>
                        </tr>
                         <tr>
                            <td>
                                <label><b>Age </b></label>
                            </td>
                            <td>
                                {{property.age}}
                            </td>
                        </tr>
                         <tr>
                            <td>
                                <label><b>Direction </b></label>
                            </td>
                            <td>
                                {{property.direction}}
                            </td>
                        </tr>
                         <tr>
                            <td>
                                <label><b>Address </b></label>
                            </td>
                            <td>
                                {{property.postadd}}
                            </td>
                        </tr>
                         <tr>
                            <td>
                                <label><b>No. of floors </b></label>
                            </td>
                            <td>
                                {{property.floor}}
                            </td>
                        </tr>

                        </tbody>
        </div>
    </div>
</div>
</div>
<!-- Map starts here-->
    <div class="col-md-8">
        <div class="thumbnail">
            <h3><strong> Location</strong> </h3>
             <div id="map"></div>
         <script>
            function initMap() {
  // The location of Uluru
        var uluru = {lat: -25.344, lng: 131.036};
      //     The map, centered at Uluru
         var map = new google.maps.Map(
        document.getElementById('map'), {zoom: 10,
        center: uluru
        });
  //The marker, positioned at Uluru
        var marker = new google.maps.Marker({
        position: uluru,
        map: map
        });
    }
    </script>
    <!--Load the API from the specified URL
    * The async attribute allows the browser to render the page while the API loads
    * The key parameter will contain your own API key (which is not needed for this tutorial)
    * The callback parameter executes the initMap() function
    -->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7PwH_mQJkNtkeQ3WjQaMorLnATmdvhKE&callback=initMap">
    </script>
        </div>
    </div>
    </body>
</html>
{% endblock %}